CC = g++
LL = for_loops_fixed.cpp MemoryHandler/MemoryHandler.cpp
OUT = a.exe 
FF = -w -std=c++20
#use G++, swap to CL for the windows c++ compiler that comes with visual studio community 2022
build:
	${CC} ${LL} -o ${OUT} ${FF}
run:
	./${OUT}
clean:
	rm -f ${OUT}